services:
  postgres:
    image: postgres
    container_name: dc5-nextjs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: dc5-nextjs-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_PORT: 5432
      ADMINER_DEFAULT_USER: ${DB_USER}
      ADMINER_DEFAULT_PASSWORD: ${DB_PASSWORD}
